#multy stage build

#тут мы просто создаем бинарь который запуститься где угодно
FROM golang:1.21-bullseye AS builder
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
#кэш папка
RUN --mount=type=cache,target="/root/.cache/go-build" go build -o /app/echo /app/cmd/echo/

FROM ubuntu:22.04
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/echo .
ENTRYPOINT ["/app/echo","default_with_builder"]